# Generated by Django 4.2.7 on 2024-01-04 08:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Asset Type',
                'db_table': 'assettype',
            },
        ),
        migrations.CreateModel(
            name='OnHandUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Supply Type',
                'db_table': 'supplytype',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('supply_id', models.CharField(default=inventory.models.default_supply_id, max_length=255, primary_key=True, serialize=False)),
                ('supply_description', models.CharField(max_length=255, unique=True)),
                ('supply_status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'DELETED')], default=1)),
                ('supply_on_hand', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('supply_reorder_lvl', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('supply_last_purchase_date', models.DateTimeField(auto_now_add=True)),
                ('supply_date_added', models.DateTimeField(auto_now_add=True)),
                ('supply_date_modified', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('supplier_id', models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='management.supplier')),
                ('supply_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplytype')),
                ('supply_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.onhandunit')),
            ],
            options={
                'verbose_name': 'Supply',
                'verbose_name_plural': 'Supplies',
                'db_table': 'supply',
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('asset_id', models.CharField(default=inventory.models.default_asset_id, max_length=255, primary_key=True, serialize=False)),
                ('asset_description', models.CharField(max_length=255, unique=True)),
                ('asset_manufacturer', models.CharField(max_length=255)),
                ('asset_model', models.CharField(max_length=255)),
                ('asset_condition', models.IntegerField(choices=[(1, 'NEW'), (2, 'GOOD'), (3, 'BAD'), (4, 'BROKEN'), (5, 'LOST')], default=1)),
                ('asset_status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'DELETED')], default=1)),
                ('asset_on_hand', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('asset_date_added', models.DateField(auto_now_add=True)),
                ('asset_date_modified', models.DateField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('asset_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.supplier')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.assettype')),
            ],
            options={
                'verbose_name': 'Assets',
                'verbose_name_plural': 'Assets',
                'db_table': 'asset',
            },
        ),
    ]
