# Generated by Django 4.2.7 on 2024-01-04 08:00

from django.db import migrations, models
import django.db.models.deletion
import transactions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Request Status',
                'db_table': 'request_status',
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Requisition Type',
                'db_table': 'requisition_type',
            },
        ),
        migrations.CreateModel(
            name='RequisitionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Requisition Status',
                'db_table': 'requisition_status',
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('req_id', models.IntegerField(default=transactions.models.default_req_id, primary_key=True, serialize=False)),
                ('req_description', models.CharField(blank=True, max_length=255, null=True)),
                ('req_date', models.DateTimeField(auto_now_add=True)),
                ('req_reviewed_by', models.CharField(default='Admin', max_length=50)),
                ('req_reviewed_date', models.DateTimeField(auto_now=True)),
                ('reviewer_notes', models.TextField(blank=True, null=True)),
                ('requestor_notes', models.TextField(blank=True, null=True)),
                ('req_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.requesttype')),
                ('request_status', models.ForeignKey(default=transactions.models.RequestStatus.get_default_status, on_delete=django.db.models.deletion.CASCADE, to='transactions.requeststatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.user_account')),
            ],
            options={
                'verbose_name': 'Requisition',
                'db_table': 'requisition',
            },
        ),
        migrations.CreateModel(
            name='Request_Supply',
            fields=[
                ('req_supply_id', models.IntegerField(default=transactions.models.default_req_supply_id, primary_key=True, serialize=False)),
                ('req_supply_qty', models.IntegerField()),
                ('req_unit_measure', models.CharField(blank=True, max_length=10, null=True)),
                ('req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.requisition')),
                ('req_status', models.ForeignKey(default=transactions.models.RequisitionStatus.get_default_status, on_delete=django.db.models.deletion.CASCADE, to='transactions.requisitionstatus')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supply')),
            ],
            options={
                'verbose_name': 'Request_Supply',
                'db_table': 'request_supply',
            },
        ),
        migrations.CreateModel(
            name='Request_Assets',
            fields=[
                ('req_asset_id', models.IntegerField(default=transactions.models.default_req_asset_id, primary_key=True, serialize=False)),
                ('req_asset_qty', models.IntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.assets')),
                ('req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.requisition')),
                ('req_status', models.ForeignKey(default=transactions.models.RequisitionStatus.get_default_status, on_delete=django.db.models.deletion.CASCADE, to='transactions.requisitionstatus')),
            ],
            options={
                'verbose_name': 'Request_Assets',
                'db_table': 'request_assets',
            },
        ),
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('purch_id', models.IntegerField(default=transactions.models.default_purch_id, primary_key=True, serialize=False)),
                ('purch_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'In Process'), (3, 'Done')], default=1)),
                ('purch_date', models.DateField(auto_now_add=True)),
                ('purch_date_modified', models.DateTimeField(auto_now=True)),
                ('req', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.requisition')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.supplier')),
            ],
            options={
                'verbose_name': 'Purchase_Order',
                'db_table': 'purchase_order',
            },
        ),
        migrations.CreateModel(
            name='Job_Order',
            fields=[
                ('job_id', models.IntegerField(default=transactions.models.default_job_id, primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=100)),
                ('worker_count', models.IntegerField(default=1)),
                ('job_start_date', models.DateField(blank=True, null=True)),
                ('job_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.requisition')),
                ('req_status', models.ForeignKey(default=transactions.models.RequisitionStatus.get_default_status, on_delete=django.db.models.deletion.CASCADE, to='transactions.requisitionstatus')),
            ],
            options={
                'verbose_name': 'Job_Order',
                'db_table': 'job_order',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.IntegerField(default=transactions.models.default_delivery_id, primary_key=True, serialize=False)),
                ('delivery_status', models.IntegerField(choices=[(1, 'In Process'), (2, 'Order Received')], default=1)),
                ('delivery_exp_date', models.DateField(blank=True, null=True)),
                ('order_receive_date', models.DateTimeField(blank=True, null=True)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('order_receive_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.user_account')),
                ('purch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.purchase_order')),
            ],
            options={
                'verbose_name': 'Delivery',
                'db_table': 'delivery',
            },
        ),
        migrations.CreateModel(
            name='Acknowledgement_Purch',
            fields=[
                ('ack_id', models.IntegerField(default=transactions.models.default_ack_purch_id, primary_key=True, serialize=False)),
                ('acknowledge_by', models.CharField(max_length=100)),
                ('acknowledge_date', models.DateTimeField(auto_now_add=True)),
                ('regstr_receive_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.delivery')),
            ],
            options={
                'verbose_name': 'Acknowledgement_Purch',
                'db_table': 'acknowledgement_purch',
            },
        ),
        migrations.CreateModel(
            name='Acknowledgement_Job',
            fields=[
                ('ack_job_id', models.IntegerField(default=transactions.models.default_ack_job_id, primary_key=True, serialize=False)),
                ('acknowledge_by', models.CharField(max_length=100)),
                ('acknowledge_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.job_order')),
            ],
            options={
                'verbose_name': 'Acknowledgement_Job',
                'db_table': 'acknowledgement_job',
            },
        ),
    ]
