# Generated by Django 4.2.7 on 2024-01-05 14:04

from django.db import migrations, models
import django.db.models.deletion
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Delivery Status',
                'db_table': 'delivery_status',
            },
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_exp_date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='reference_id',
        ),
        migrations.AlterField(
            model_name='request_supply',
            name='req_unit_measure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DeliverySupply',
            fields=[
                ('del_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('del_status', models.ForeignKey(default=transactions.models.DeliveryStatus.get_default_status, on_delete=django.db.models.deletion.CASCADE, to='transactions.deliverystatus')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.delivery')),
                ('req_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.request_supply')),
            ],
            options={
                'verbose_name': 'Delivery_Supply',
                'db_table': 'delivery_supply',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAsset',
            fields=[
                ('del_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('del_status', models.ForeignKey(default=transactions.models.DeliveryStatus.get_default_status, on_delete=django.db.models.deletion.CASCADE, to='transactions.deliverystatus')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.delivery')),
                ('req_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.request_assets')),
            ],
            options={
                'verbose_name': 'Delivery_Asset',
                'db_table': 'delivery_asset',
            },
        ),
    ]
