# Generated by Django 4.2.7 on 2024-01-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_purchase_order_purch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='purch_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Cancelled'), (3, 'Approved')], default=1),
        ),
    ]
